import React, { createContext, useContext, useEffect } from 'react';
import { useData } from './DataContext';
import type { AppLanguage } from '../lib/types';

type Language = AppLanguage;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    dashboard: "Tableau de bord",
    students: "Élèves",
    employees: "Personnel",
    parents: "Parents",
    schedules: "Scolarité",
    communication: "Communication",
    statistics: "Statistiques",
    certificates: "Certificats",
    certificate_registry: "Registre",
    school_header: "Entête",
    login: "Connexion",
    username: "Utilisateur",
    password: "Mot de passe",
    login_btn: "Se connecter",
    welcome: "Bienvenue",
    total_students: "Total Élèves",
    total_staff: "Total Staff",
    upcoming_exams: "Examens",
    unread_messages: "Messages",
    quick_actions: "Actions Rapides",
    recent_activity: "Activité Récente",
    add_student: "Ajouter Élève",
    import_excel: "Import Excel",
    search: "Rechercher...",
    call: "Appeler",
    whatsapp: "WhatsApp",
    messenger: "Messenger",
    admin: "Admin",
    teacher: "Prof",
    logout: "Déconnexion",
    classes: "Classes",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    confirm_delete: "Êtes-vous sûr de vouloir supprimer ?",
    urgent: "Urgent",
    info: "Info",
    normal: "Normal",
    no_data: "Aucune donnée disponible",
    subject: "Sujet",
    message: "Message",
    send: "Envoyer",
    full_name: "Nom complet",
    parent_phone: "Tél. Parent",
    birth_date: "Date Naissance",
    role: "Poste",
    type: "Type",
    phone: "Téléphone",
    all: "Tous",
    upload_timetable: "Publier Emploi du Temps",
    exam_schedule: "Planning Examens",
    sessions: "Sessions",
    room: "Salle",
    supervisor: "Surveillant",
    announcements: "Annonces",
    new_announcement: "Nouvelle Annonce",
    mark_read: "Marquer comme lu",
    success_import: "Importation réussie",
    error_import: "Erreur d'importation",
    alphabetical_sort: "Tri alphabétique automatique",
    demo_creds: "Identifiants démo",
    print_export: "Imprimer / Exporter PDF",
    select_file: "SÉLECTIONNER UN FICHIER (Excel / Word / PDF / Image)",
    drag_drop: "Ou glisser-déposer ici",
    upload_exam_schedule: "Publier Planning Examens",
    trimester: "Trimestre",
    finance: "Finance",
    attendance: "Présence",
    roll_call: "Appel Numérique",
    remote_requests: "Demandes à distance",
    student_directory: "Répertoire Élèves",
    select_class: "Sélectionner Classe",
    present: "Présent",
    absent: "Absent",
    send_reminder: "Envoyer Rappel",
    tuition_arrears: "Arriérés Scolarité",
    payment_reminder: "الرجاء دفع المعلوم الشهري المتخلد بالذمة وشكرا لتفهمكم",
    school_news: "Actualités de la Providence",
    post_news: "Publier une Actualité",
    news_title: "TITRE DE L'ACTUALITÉ",
    news_description: "DESCRIPTION",
    news_category: "CATÉGORY",
    media_url: "LIEN VIDÉO / SOURCE EXTERNE",
    publish: "Publier",
    event: "Événement",
    announcement: "Annonce",
    read_more: "En savoir plus",
    fill_all_fields: "Veuillez remplir tous les champs obligatoires",
    homework: "Travail à faire",
    create_homework: "Créer un devoir",
    target_classes: "Classes cibles (multi-sélection)",
    no_homework: "Aucun devoir assigné pour le moment",
    homework_title: "Titre du devoir",
    homework_description: "Description",
    select_classes: "Sélectionner les classes",
    attach_file: "Joindre un fichier (optionnel)",
    publish_homework: "Publier le devoir",
    assigned_to: "Assigné aux classes :",
    created: "Créé le",
    news_feed: "Actualités",
    create_post: "Créer un post",
    delete_post: "Supprimer le post",
    edit_post: "Modifier le post",
    comment: "commentaire",
    like: "J'aime",
    audience_target: "Cible du public",
    publish_post: "Publier le post",
    no_posts_yet: "Aucun post pour le moment",
    images_files_optional: "Images / Fichiers (optionnel)",
    add_comment: "Ajouter un commentaire...",
    edit_post_title: "Modifier le post",
    save_changes: "Enregistrer les modifications",
    confirm_delete_post: "Supprimer ce post ?",
    action_irreversible: "Cette action est irréversible.",
    delete_permanently: "Supprimer définitivement",
    reduce: "Réduire",
    eduserv: "Eduserv",
    eduserv_integration: "Intégration Eduserv",
    api_sync_section: "Synchronisation API",
    eduserv_credentials: "Identifiants / Clés API Eduserv",
    api_key: "Clé API",
    api_secret: "Secret API",
    sync_now: "Synchroniser avec Eduserv",
    syncing: "Synchronisation en cours...",
    import_students: "Importer les élèves",
    export_data: "Exporter les données",
    drag_drop_ministry: "Glissez-déposez le fichier Excel/CSV du portail ministère ici ou cliquez pour sélectionner",
    export_attendance_report: "Exporter Rapport Présence (format Ministère)",
    export_grades_template: "Exporter Notes / Bulletins (template officiel)",
    status_logs: "Logs de synchronisation",
    no_logs_yet: "Aucun log pour le moment. Lancez une sync ou import.",
    log_sync_start: "[INFO] Début synchronisation Eduserv...",
    log_credentials_ok: "[OK] Identifiants vérifiés",
    log_import_complete: "[OK] {count} élèves importés",
    log_sync_complete: "[OK] Synchronisation terminée",
    log_export_done: "[OK] Export généré: "
  },
  ar: {
    dashboard: "لوحة التحكم",
    students: "الطلاب",
    employees: "الموظفون",
    parents: "أولياء الأمور",
    schedules: "الجدول المدرسي",
    communication: "التواصل",
    statistics: "الإحصائيات",
    certificates: "الشهادات",
    certificate_registry: "السجل",
    school_header: "هوية المدرسة",
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login_btn: "دخول",
    welcome: "مرحباً",
    total_students: "إجمالي الطلاب",
    total_staff: "إجمالي الموظفين",
    upcoming_exams: "الامتحانات",
    unread_messages: "الرسائل",
    quick_actions: "إجراءات سريعة",
    recent_activity: "النشاط الأخير",
    add_student: "إضافة طالب",
    import_excel: "استيراد Excel",
    search: "بحث...",
    call: "اتصال",
    whatsapp: "واتساب",
    messenger: "مسنجر",
    admin: "مدير",
    teacher: "أستاذ",
    logout: "خروج",
    classes: "الأقسام",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    confirm_delete: "هل أنت متأكد من الحذف؟",
    urgent: "عاجل",
    info: "معلومة",
    normal: "عادي",
    no_data: "لا توجد بيانات",
    subject: "الموضوع",
    message: "الرسالة",
    send: "إرسال",
    full_name: "الاسم الكامل",
    parent_phone: "هاتف ولي الأمر",
    birth_date: "تاريخ الازدياد",
    role: "المهمة",
    type: "النوع",
    phone: "الهاتف",
    all: "الكل",
    upload_timetable: "نشر جدول الحصص",
    exam_schedule: "جدول الامتحانات",
    sessions: "الدورات",
    room: "القاعة",
    supervisor: "المراقب",
    announcements: "الإعلانات",
    new_announcement: "إعلان جديد",
    mark_read: "تحديد كمقروء",
    success_import: "تم الاستيراد بنجاح",
    error_import: "خطأ في الاستيراد",
    alphabetical_sort: "ترتيب أبجدي تلقائي",
    demo_creds: "بيانات التجربة",
    print_export: "طباعة / تصدير PDF",
    select_file: "اختر ملف (Excel / Word / PDF / صورة)",
    drag_drop: "أو اسحب الملف هنا",
    upload_exam_schedule: "نشر جدول الامتحانات",
    trimester: "الفصل الدراسي",
    finance: "المالية",
    attendance: "الحضور",
    roll_call: "النداء الرقمي",
    remote_requests: "طلبات عن بعد",
    student_directory: "دليل الطلاب",
    select_class: "اختر القسم",
    present: "حاضر",
    absent: "غائب",
    send_reminder: "إرسال تذكير",
    tuition_arrears: "أقساط متأخرة",
    payment_reminder: "الرجاء دفع المعلوم الشهري المتخلد بالذمة وشكرا لتفهمكم",
    school_news: "أخبار المدرسة",
    post_news: "نشر خبر",
    news_title: "عنوان الخبر",
    news_description: "الوصف",
    news_category: "الفئة",
    media_url: "رابط فيديو / مصدر خارجي",
    publish: "نشر",
    event: "حدث",
    announcement: "إعلان",
    read_more: "اقرأ المزيد",
    fill_all_fields: "يرجى ملء جميع الحقول المطلوبة",
    homework: "الواجبات المدرسية",
    create_homework: "إنشاء واجب",
    target_classes: "الفصول المستهدفة (اختيار متعدد)",
    no_homework: "لا توجد واجبات مخصصة حالياً",
    homework_title: "عنوان الواجب",
    homework_description: "الوصف",
    select_classes: "اختيار الفصول",
    attach_file: "إرفاق ملف (اختياري)",
    publish_homework: "نشر الواجب",
    assigned_to: "مخصص للفصول :",
    created: "تم الإنشاء في",
    news_feed: "الأخبار",
    create_post: "إنشاء منشور",
    delete_post: "حذف المنشور",
    edit_post: "تعديل المنشور",
    comment: "تعليق",
    like: "إعجاب",
    audience_target: "الجمهور المستهدف",
    publish_post: "نشر المنشور",
    no_posts_yet: "لا توجد منشورات بعد",
    images_files_optional: "صور / ملفات (اختياري)",
    add_comment: "أضف تعليق...",
    edit_post_title: "تعديل المنشور",
    save_changes: "حفظ التغييرات",
    confirm_delete_post: "حذف هذا المنشور؟",
    action_irreversible: "هذا الإجراء لا يمكن التراجع عنه.",
    delete_permanently: "حذف نهائي",
    reduce: "تصغير",
    eduserv: "Eduserv",
    eduserv_integration: "تكامل Eduserv",
    api_sync_section: "مزامنة API",
    eduserv_credentials: "بيانات اعتماد / مفاتيح API Eduserv",
    api_key: "مفتاح API",
    api_secret: "سر API",
    sync_now: "مزامنة مع Eduserv",
    syncing: "جاري المزامنة...",
    import_students: "استيراد الطلاب",
    export_data: "تصدير البيانات",
    drag_drop_ministry: "اسحب ملف Excel/CSV من بوابة الوزارة هنا أو انقر للاختيار",
    export_attendance_report: "تصدير تقرير الحضور (تنسيق الوزارة)",
    export_grades_template: "تصدير الدرجات / الشهادات (قالب رسمي)",
    status_logs: "سجلات المزامنة",
    no_logs_yet: "لا توجد سجلات بعد. قم بمزامنة أو استيراد.",
    log_sync_start: "[INFO] بدء مزامنة Eduserv...",
    log_credentials_ok: "[OK] تم التحقق من بيانات الاعتماد",
    log_import_complete: "[OK] تم استيراد {count} طالب",
    log_sync_complete: "[OK] اكتملت المزامنة",
    log_export_done: "[OK] تم إنشاء التصدير: "
  },
  en: {
    dashboard: "Dashboard",
    students: "Students",
    employees: "Staff",
    parents: "Parents",
    schedules: "Academics",
    communication: "Communication",
    statistics: "Statistics",
    certificates: "Certificates",
    certificate_registry: "Registry",
    school_header: "Header",
    login: "Login",
    username: "Username",
    password: "Password",
    login_btn: "Sign In",
    welcome: "Welcome",
    total_students: "Total Students",
    total_staff: "Total Staff",
    upcoming_exams: "Exams",
    unread_messages: "Messages",
    quick_actions: "Quick Actions",
    recent_activity: "Recent Activity",
    add_student: "Add Student",
    import_excel: "Import Excel",
    search: "Search...",
    call: "Call",
    whatsapp: "WhatsApp",
    messenger: "Messenger",
    admin: "Admin",
    teacher: "Teacher",
    logout: "Logout",
    classes: "Classes",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete?",
    urgent: "Urgent",
    info: "Info",
    normal: "Normal",
    no_data: "No data available",
    subject: "Subject",
    message: "Message",
    send: "Send",
    full_name: "Full Name",
    parent_phone: "Parent Phone",
    birth_date: "Birth Date",
    role: "Role",
    type: "Type",
    phone: "Phone",
    all: "All",
    upload_timetable: "Publish Timetable",
    exam_schedule: "Exam Schedule",
    sessions: "Sessions",
    room: "Room",
    supervisor: "Supervisor",
    announcements: "Announcements",
    new_announcement: "New Announcement",
    mark_read: "Mark as read",
    success_import: "Import successful",
    error_import: "Import error",
    alphabetical_sort: "Automatic alphabetical sorting",
    demo_creds: "Demo credentials",
    print_export: "Print / Export PDF",
    select_file: "SELECT A FILE (Excel / Word / PDF / Image)",
    drag_drop: "Or drag and drop here",
    upload_exam_schedule: "Publish Exam Schedule",
    trimester: "Trimester",
    finance: "Finance",
    attendance: "Attendance",
    roll_call: "Digital Roll Call",
    remote_requests: "Remote Requests",
    student_directory: "Student Directory",
    select_class: "Select Class",
    present: "Present",
    absent: "Absent",
    send_reminder: "Send Reminder",
    tuition_arrears: "Tuition Arrears",
    payment_reminder: "الرجاء دفع المعلوم الشهري المتخلد بالذمة وشكرا لتفهمكم",
    school_news: "School News",
    post_news: "Post News",
    news_title: "NEWS TITLE",
    news_description: "DESCRIPTION",
    news_category: "CATEGORY",
    media_url: "VIDEO LINK / EXTERNAL SOURCE",
    publish: "Publish",
    event: "Event",
    announcement: "Announcement",
    read_more: "Read more",
    fill_all_fields: "Please fill all required fields",
    homework: "Homework",
    create_homework: "Create Homework",
    target_classes: "Target Classes (multi-select)",
    no_homework: "No homework assignments yet",
    homework_title: "Homework Title",
    homework_description: "Description",
    select_classes: "Select Classes",
    attach_file: "Attach File (optional)",
    publish_homework: "Publish Homework",
    assigned_to: "Assigned to classes:",
    created: "Created:",
    news_feed: "News Feed",
    create_post: "Create Post",
    delete_post: "Delete Post",
    edit_post: "Edit Post",
    comment: "comment",
    like: "Like",
    audience_target: "Audience Target",
    publish_post: "Publish Post",
    no_posts_yet: "No posts yet",
    images_files_optional: "Images / Files (optional)",
    add_comment: "Add a comment...",
    edit_post_title: "Edit Post",
    save_changes: "Save Changes",
    confirm_delete_post: "Delete this post?",
    action_irreversible: "This action is irreversible.",
    delete_permanently: "Delete Permanently",
    reduce: "Reduce",
    eduserv: "Eduserv",
    eduserv_integration: "Eduserv Integration",
    api_sync_section: "API Sync Section",
    eduserv_credentials: "Eduserv Credentials / API Keys",
    api_key: "API Key",
    api_secret: "API Secret",
    sync_now: "Sync Now with Eduserv",
    syncing: "Syncing...",
    import_students: "Import Students",
    export_data: "Export Data",
    drag_drop_ministry: "Drag & drop Excel/CSV file from ministry portal here or click to select",
    export_attendance_report: "Export Attendance Report (Ministry Format)",
    export_grades_template: "Export Grades / Reports (Official Template)",
    status_logs: "Synchronization Logs",
    no_logs_yet: "No logs yet. Perform a sync or import.",
    log_sync_start: "[INFO] Starting Eduserv sync...",
    log_credentials_ok: "[OK] Credentials verified",
    log_import_complete: "[OK] {count} students imported",
    log_sync_complete: "[OK] Sync complete",
    log_export_done: "[OK] Export generated: "
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { appPreferences, updateAppLanguage } = useData();
  const language = appPreferences.language;

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage: updateAppLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};